apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: <ACR_LOGIN_SERVER>/customer_service:latest
          ports:
            - containerPort: 8002
          env:
            - name: POSTGRES_HOST
              value: customer-db
            - name: POSTGRES_DB
              value: customers
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP