# .github/workflows/frontend-cd.yml

name: CD - Deploy Frontend to AKS

on:
  push:
    branches:
      - main

jobs:
  call_backend_cd:
    uses: ./.github/workflows/backend-cd.yml
    secrets: inherit

  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production
    needs: call_backend_cd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context (get AKS credentials)
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Inject Backend service names into frontend/main.js
        run: |
          echo "Injecting internal backend service names into frontend/main.js"
          sed -i "s|_PRODUCT_API_URL_|product-service-w10-aks|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|order-service-w10-aks|g" frontend/main.js
          sed -i "s|_CUSTOMER_API_URL_|customer-service-w10-aks|g" frontend/main.js
          
          # Display the modified file content for debugging
          echo "--- Modified main.js content ---"
          cat frontend/main.js
          echo "---------------------------------"

      - name: Deploy Frontend to Production Environment
        run: |
          kubectl apply -f k8s/frontend.yaml -n production

      - name: Logout from Azure
        run: az logout
        if: always()